pybullet_simulation:
  simulation_step_time: 0.005
  real_step_time : 0.005
  camera_init:
    distance: 1.00
    yaw: 1.20
    pitch: -29.00
    target_position: [-0.02,0.70,-0.32]

  joint_state_publish_rate: 250
  joint_target_publish_rate: 250

  robots:
    $(arg robot_name):
      start_position: [0,0,0]
      start_orientation: [0,0,0]
      fixed: 1    # 1 to fix robot to world, 0 to spawn it unfixed
